name: Build Dev Image

on:
  workflow_dispatch:

jobs:
  build_dev_image:
    uses: ./.github/workflows/build_image.yml
    with:
      version: dev
      ENV: development
      API_URL: 'http://localhost:3000'
      push: true
    secrets: inherit
